name: Lint


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  frontend-lint:
    name: Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run:
        - cd frontend
        - npm ci
        - npm run lint

  backend-lint:
    name: Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run:
        - cd backend
        - npm ci
        - npm run lint
  

